# Generated by Django 4.0.1 on 2022-02-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadimg',
            name='url_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/img/'),
        ),
    ]
